# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 61e0a4e
_src_path: https://github.com/ImshaBy/ci_cd_template
build_args: true
domain: admin.imsha.by
namespace: admin
project_name: admin
