name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
#        env:
#            DATE: $(date +%Y-%m-%d-%T)
        steps:
            - uses: actions/checkout@v2
            - name: Create ssh-key file
              run: |
                mkdir ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
            - name: Use NodeJS v.12
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: NPM install and build
              run: npm ci && npm run build
            - name: TAR dist folder
              run: tar -czf release.tar.gz ./dist
            - name: Copy to server
              run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" /dist ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/www/static/
