name: Deploy to Production

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL_PRD}}
      REACT_APP_FUSION_ADDRESS: ${{secrets.REACT_APP_FUSION_ADDRESS}}
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS v.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: NPM install
        run: npm ci

      - name: NPM build
        run: CI='' npm run build

      - name: Yandex Cloud Deploy
        uses: nekitcorp/yandex-storage-website-action@v2
        with:
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          clear: true
          working-directory: build
          include: |
            **/*