name: Deploy to QA

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}

      REACT_APP_FUSION_CLIENT_ID: ${{secrets.REACT_APP_FUSION_CLIENT_ID}}
      REACT_APP_FUSION_CLIENT_SECRET: ${{secrets.REACT_APP_FUSION_CLIENT_SECRET}}
      REACT_APP_FUSION_REDIRECTED_URI: ${{secrets.REACT_APP_FUSION_REDIRECTED_URI}}
      REACT_APP_FUSION_API_KEY: ${{secrets.REACT_APP_FUSION_API_KEY}}
      REACT_APP_FUSION_ADDRESS: ${{secrets.REACT_APP_FUSION_ADDRESS}}
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS v.14.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: NPM install
        run: npm ci

      - name: NPM build
        run: CI='' npm run build

      - name: Check Lint
        run: npm run lint

      - name: Archive QA artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ~/work/imshaby-admin/imshaby-admin/build
      
      - name: Yandex Cloud Deploy
        uses: nekitcorp/yandex-storage-website-action@v2
        with:
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          clear: true
          working-directory: build
          include: |
            **/*
