name: Deploy to QA

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}

      REACT_APP_FUSION_CLIENT_ID: ${{secrets.REACT_APP_FUSION_CLIENT_ID}}
      REACT_APP_FUSION_CLIENT_SECRET: ${{secrets.REACT_APP_FUSION_CLIENT_SECRET}}
      REACT_APP_FUSION_REDIRECTED_URI: ${{secrets.REACT_APP_FUSION_REDIRECTED_URI}}
      REACT_APP_FUSION_API_KEY: ${{secrets.REACT_APP_FUSION_API_KEY}}
      REACT_APP_FUSION_ADDRESS: ${{secrets.REACT_APP_FUSION_ADDRESS}}
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS v.14.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: NPM install
        run: npm ci

      - name: NPM build
        run: CI='' npm run build

      - name: Check Lint
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: git-to-jelastic
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          config: |
            Host *
              IdentityFile ~/.ssh/git-to-jelastic
              HostkeyAlgorithms +ssh-rsa
              PubkeyAcceptedAlgorithms +ssh-rsa

      - name: Deploy with rsync (QA)
        run: rsync -avz --rsh='ssh -o StrictHostKeyChecking=no -i ~/.ssh/git-to-jelastic -p3022' --delete-before build/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/www/static/
