name: Deploy Admin to Prod (Digital Ocean Droplet)

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      VITE_API_URL: ${{vars.VITE_API_URL}}
      VITE_AUTH_DOMAIN: ${{vars.VITE_AUTH_DOMAIN}}
      VITE_AUTH_CLIENT_ID: ${{secrets.VITE_AUTH_CLIENT_ID}}
      VITE_FUSION_ADDRESS: ${{vars.VITE_FUSION_ADDRESS}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Create ssh-key file
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com

      - name: Use NodeJS v.18.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: NPM install
        run: npm ci

      - name: NPM build
        run: CI='' npm run build

      - name: List of files
        run: cd ./dist && ls -la

      - name: Copy to server
        run: rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ vars.STATIC_PATH }}
  
  create_release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Export LATEST_TAG
        run: |
          echo "LATEST_TAG=$(curl -qsSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.event.inputs.ref }}
          toTag: ${{ env.LATEST_TAG }}
          writeToFile: false
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.ref }}
          name: Release ${{ github.event.inputs.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
