name: Deploy Admin to Prod (Digital Ocean Droplet)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      REACT_APP_API_URL: ${{vars.REACT_APP_API_URL}}
      REACT_APP_AUTH_DOMAIN: ${{vars.REACT_APP_AUTH_DOMAIN}}
      REACT_APP_AUTH_CLIENT_ID: ${{secrets.REACT_APP_AUTH_CLIENT_ID}}
      REACT_APP_FUSION_ADDRESS: ${{vars.REACT_APP_FUSION_ADDRESS}}
    steps:
      - uses: actions/checkout@v4

      - name: Create ssh-key file
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com

      - name: Use NodeJS v.18.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: NPM install
        run: npm ci

      - name: NPM build
        run: CI='' npm run build

      - name: List of files
        run: cd ./dist && ls -la

      - name: Copy to server
        run: rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ vars.STATIC_PATH }}
